### ISSUE TITLE
Cant find show: Supernatural

### ISSUE THREAD

**Issue by daddydeadpool** [lokenx/plexrequests-meteor#506] opened 2017-11-07 11:01 UTC
When searching for the show Supernatural I get a small box stating "No results found"

**Comment by rigrassm** [comment] 2017-11-07 14:02
Thanks for the report, I've noticed this with a couple shows in the past
but they were more fringe cases caused by TVMaze not having a TMDB ID in
their database. I'm not sure if that's what happening here (haven't been
able to see what the search results are returning yet) or if it's actually
an issue with how we're doing the search.

**Comment by daddydeadpool** [comment] 2017-11-08 00:34
thank you for the reply, so far supernatural is the only one I haven't been able to find so I cant complain.

**Comment by jackaroo9** [comment] 2017-11-14 17:44
Found same issue with Knightfall (2017)

**Comment by lokenx** [comment] 2017-12-14 01:07
Hmm noticed that too, even though there API is returning the data correctly. I'll see if I've some time to have a quick look, API could've changed or we're doing something weird with the results.

**Comment by rigrassm** [comment] 2017-12-14 01:10
I know we do have a few things going on under the hood for filtering out
bad results. I may spin up a test instance with some extra debugging code
slapped in to see what the deal is.

**Comment by rigrassm** [comment] 2018-02-21 01:48
Fixed by #524 

Issue was being caused by some of the search results not having a description and then trying to run a str.replace on it. Caused the search function to bail out leaving no results to be returned. Just added some logic to handle cases when a search result item doesn't return an overview.

**Closed by rigrassm** 2018-02-21 01:48 UTC
