### ISSUE TITLE
Add ability to request individual episodes or individual seasons for TV shows

### ISSUE THREAD

**Issue by moonjazz** [lokenx/plexrequests-meteor#429] opened 2017-01-13 05:54 UTC
Hey all!

First off thanks for a wonderful piece of software, really enhances the media experience for my whole family! Could not thank you enough, I hope to be able contribute soon. Anyways, as the title says, I think it would be a nice enhancement to be able to request individual episodes/certain seasons that the user can choose oppose to only being able to download EVERYTHING or only new things. I've run into this a few times, every now and again and I really think it would enhance the user experience for everyone using PlexRequests. 

Thanks!

**Comment by rigrassm** [comment] 2017-01-25 01:14
Duplicate of #345, plan on getting around to this one soon.

**Comment by moonjazz** [comment] 2017-02-06 06:13
@rigrassm sorry about the duplicate, but thanks for the update <3

**Comment by rigrassm** [comment] 2017-02-19 20:15
Closing duplicate request.

**Closed by rigrassm** 2017-02-19 20:15 UTC
Labels: duplicate, enhancement, planned
