### ISSUE TITLE
[req] Give a warning message when add a movie/serie on wrong category

### ISSUE THREAD

**Issue by whitecollar17** [lokenx/plexrequests-meteor#248] opened 2016-01-29 23:50 UTC
hi,

it is possible to display a warning message if a user requests a movie or series under the wrong category tries to request ?

Or is it possible to make it impossible to requets a film , for example, under the category of series or vice versa?

**Comment by lokenx** [comment] 2016-01-30 00:52
What you mean wrong category? Not sure I follow.

**Comment by Kryptonit3** [comment] 2016-01-30 06:49
he may be referring to SabNZBd categories (or another usenet downloader) and if that is the case, those settings should be set in the actual clients themselves (CouchPotato category settings and Sonarr/SickRage category settings).

![cp](http://i.snag.gy/qAPES.jpg)

**Comment by whitecollar17** [comment] 2016-02-08 20:17
No, i mean: when you chose the wrong subject: Film instead of TV show or tv show instead of film

**Comment by lokenx** [comment] 2016-02-09 00:05
You mean you request a tv show or movie that is in both lists but you wanted the movie but requested the tv?

**Comment by whitecollar17** [comment] 2016-02-09 07:11
Yes, maybe it is possible to have a warming message or to make it
inpossible?
Op 9 feb. 2016 1:05 AM schreef "loken" <notifications@github.com>:

**Comment by lokenx** [comment] 2016-02-09 16:44
I still don't follow. Allowing users to delete or undo incorrect requests is definitely something I can look into adding, but making it impossible for them to chose the wrong subject?

If they search CSI movies and tv shows will come up (in separate lists), but they can't request the tv show under the movies section or vice versa, and I have no idea which they intended to request so I couldn't warn them about anything or stop it happening.

We could make it clearer which section they're in, movie or tv, but that's really it.

**Comment by whitecollar17** [comment] 2016-02-18 16:29
Hi,

Sorry for my bad English.
You can add a TV show under the movies section and vice versa. That is the problem.

Maybe it's better to make a real button above the search bar to select first  a TV show or movie .
instead of a text under the search bar

**Comment by lokenx** [comment] 2016-02-18 20:38
But hitting the movie or tv show button updates the results to only show tv shows or movies, it should be changing results. Is it not changing results when you hit tv/movie?

See GIF below, is this not happening for you?

![gif demo](http://g.recordit.co/hu7aPsseiR.gif)

**Comment by lokenx** [comment] 2016-02-20 21:23
Still really not sure what the issue is here, I'm sorry. Closing, but please comment if I'm missing something, or things don't look like the above GIF for you.

**Closed by lokenx** 2016-02-20 21:23 UTC
