### ISSUE TITLE
PushBullet Device ID for Notifications

### ISSUE THREAD

**Issue by lokenx** [lokenx/plexrequests-meteor#470] opened 2017-05-01 00:12 UTC
> Thank you for all your hard work. Plexrequests is great! I just have one feature request. In Sonarr and Radarr for pushbullet notifications I have the option to add device ID which is necessary for me because pushbullet on OSX is buggy (has not been updated in ages) but I still need to use it for pushing websites. I only want notifications to go to my iphone which I am able to do with Radarr and Sonarr, but with Plexrequests I cannot do that. It goes to all devices which does not work well for me. Could you please add this in?

**Comment by rigrassm** [comment] 2017-06-24 01:10
Should be a simple addition. I'll add it to my to-do list.

**Comment by rigrassm** [comment] 2017-06-24 01:14
Closing as a duplicate of #464

**Closed by rigrassm** 2017-06-24 01:14 UTC
Labels: duplicate
