### ISSUE TITLE
Unable to Approve Request through SickRage

### ISSUE THREAD

**Issue by sirelewop14** [lokenx/plexrequests-meteor#213] opened 2015-12-31 15:30 UTC
Hey I just recently found this software and really love it. You guys seem to have a great community here.

Currently, I have PlexRequests setup on OSX10.11.2 w/ meteor 1.2.1.
When I try to add a show through PlexRequests, it will search and add it to the approval list, but when I click approve, the logs show "Error adding to sickrage." SickRage is connected, and the test button on the setup page for it within PlexRequests works fine. I can even see the app logging in in SIckRage's logs.

The app works great with couchpotato however for movies. So that's awesome!

Here are my logs from the terminal, i did run a meteor update after looking at previous posts from other users here, it made my errors shorter, but did not resolve the problem.

jeeves:plexrequests-meteor rhys$ meteor update
This project is already at Meteor 1.2.1, the latest release.
                                              
Changes to your project's package version selections from updating package versions:
                                              
aldeed:autoform            upgraded from 5.7.1 to 5.8.1
aldeed:collection2         upgraded from 2.5.0 to 2.8.0
aldeed:collection2-core    added, version 1.0.0
aldeed:schema-deny         added, version 1.0.1
aldeed:schema-index        added, version 1.0.1
aldeed:simple-schema       upgraded from 1.3.3 to 1.5.3
aslagle:reactive-table     upgraded from 0.8.18 to 0.8.21
fortawesome:fontawesome    upgraded from 4.4.0 to 4.5.0
lokenx:sonarrwrapper       upgraded from 0.0.4 to 0.0.7
mdg:validation-error       added, version 0.2.0
raix:eventemitter          added, version 0.1.3
softwarerero:accounts-t9n  upgraded from 1.1.6 to 1.1.7
useraccounts:bootstrap     upgraded from 1.12.4 to 1.13.1
useraccounts:core          upgraded from 1.12.4 to 1.13.1

                                              
The following top-level dependencies were not updated to the very latest version available:
 * iron:core 1.0.8 (1.0.11 is available)      
 * iron:router 1.0.10 (1.0.12 is available)   
 * twbs:bootstrap 4.0.0-alpha (4.0.0-alpha2 is available)
                                              
Newer versions of the following indirect dependencies are available:
 * iron:controller 1.0.8 (1.0.12 is available)
 * iron:dynamic-template 1.0.8 (1.0.12 is available)
 * iron:layout 1.0.8 (1.0.12 is available)    
 * iron:location 1.0.9 (1.0.11 is available)  
 * iron:middleware-stack 1.0.10 (1.0.11 is available)
 * iron:url 1.0.9 (1.0.11 is available)       
 * softwarerero:accounts-t9n 1.1.7 (1.2.0 is available)
To update one or more of these packages, pass their names to `meteor update`.
jeeves:plexrequests-meteor rhys$ meteor       
[[[[[ /Applications/PlexRequests/plexrequests-meteor ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
I20151231-10:17:31.920(-5)? Exceeded maxRedirects. Probably stuck in a redirect loop http://10.11.12.5:8081/
W20151231-10:17:31.913(-5)? (STDERR) (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
W20151231-10:17:31.916(-5)? (STDERR) Trace
W20151231-10:17:31.917(-5)? (STDERR)     at Request.addListener (events.js:160:15)
W20151231-10:17:31.917(-5)? (STDERR)     at Request.init (/Users/rhys/.meteor/packages/http/.1.1.1.rwvb9p++os+web.browser+web.cordova/npm/node_modules/request/request.js:618:8)
W20151231-10:17:31.917(-5)? (STDERR)     at Request.onRequestResponse (/Users/rhys/.meteor/packages/http/.1.1.1.rwvb9p++os+web.browser+web.cordova/npm/node_modules/request/request.js:1127:10)
W20151231-10:17:31.917(-5)? (STDERR)     at ClientRequest.emit (events.js:95:17)
W20151231-10:17:31.917(-5)? (STDERR)     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1689:21)
W20151231-10:17:31.917(-5)? (STDERR)     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
W20151231-10:17:31.917(-5)? (STDERR)     at Socket.socketOnData [as ondata] (http.js:1584:20)
W20151231-10:17:31.918(-5)? (STDERR)     at TCP.onread (net.js:528:27)
W20151231-10:17:31.918(-5)? (STDERR) (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
W20151231-10:17:31.918(-5)? (STDERR) Trace
W20151231-10:17:31.918(-5)? (STDERR)     at Request.addListener (events.js:160:15)
W20151231-10:17:31.918(-5)? (STDERR)     at Request.start (/Users/rhys/.meteor/packages/http/.1.1.1.rwvb9p++os+web.browser+web.cordova/npm/node_modules/request/request.js:937:8)
W20151231-10:17:31.919(-5)? (STDERR)     at Request.end (/Users/rhys/.meteor/packages/http/.1.1.1.rwvb9p++os+web.browser+web.cordova/npm/node_modules/request/request.js:1635:10)
W20151231-10:17:31.919(-5)? (STDERR)     at end (/Users/rhys/.meteor/packages/http/.1.1.1.rwvb9p++os+web.browser+web.cordova/npm/node_modules/request/request.js:676:14)
W20151231-10:17:31.919(-5)? (STDERR)     at Object._onImmediate (/Users/rhys/.meteor/packages/http/.1.1.1.rwvb9p++os+web.browser+web.cordova/npm/node_modules/request/request.js:690:7)
W20151231-10:17:31.919(-5)? (STDERR)     at processImmediate [as _immediateCallback] (timers.js:363:15)
W20151231-10:18:24.868(-5)? (STDERR) error: Error adding to SickRage
W20151231-10:18:34.095(-5)? (STDERR) error: Error adding to SickRage

Thanks in advance!

Rhys

**Comment by kerbysj** [comment] 2016-01-01 20:19
Im also unable to add shows to sickrage. However the only error i get is  "error: Error adding to SickRage"

**Comment by lokenx** [comment] 2016-01-02 11:54
This message is concerning:

`Exceeded maxRedirects. Probably stuck in a redirect loop http://10.11.12.5:8081/`

The address and port is correct, you've no forwards or redirects in place?

Do you know if you can access the SickRage API just via a browser? (Can't get you the URL, on holiday)

Is it on same machine or a different machine?

**Comment by sirelewop14** [comment] 2016-01-02 15:54
Nope, none that i can think of. I can access Sickrage web interface fine, and the API seems to work for an app on my phone. The Software is running on the same machine, I could try localhost instead of the address.

**Comment by ThePierce** [comment] 2016-01-08 10:52
Hi Lokenx,

Same isse here as what kerbysj is experiencing. Sickrage doesn't show any sign of incoming traffic from plexrequests. Plexrequests is giving me the error:  "error: Error adding to SickRage" However my settings within Plexrequests are setup correctly as it can connect succesfully to Sickrage.

**Comment by lokenx** [comment] 2016-01-08 13:48
Can you add things directly in SickRage? Version info would be helpful too.

**Comment by duramato** [comment] 2016-01-08 13:50
Hey guys what port are you using for SickRage?

**Comment by ThePierce** [comment] 2016-01-08 13:57
Hi Lokenx,

I can add shows directly to Sickrage, Version is the latest from github. 
(commit: 9226ba5efba06fb9defc5272f03dae5d6d1c4145 installed) 

@duramato
Port 8004

**Comment by lokenx** [comment] 2016-01-08 13:57
Which repo, old or new one?
		
        
		
		 ---- On Fri, 08 Jan 2016 08:57:07 -0500  notifications@github.com  wrote ----Hi Lokenx,
I can add shows directly to Sickrage, Version is the latest from github. 
(commit: 9226ba5efba06fb9defc5272f03dae5d6d1c4145 installed) 
@duramato
Port 8004

**Comment by ThePierce** [comment] 2016-01-08 13:58
https://github.com/SiCKRAGETV/SickRage.git

**Comment by duramato** [comment] 2016-01-08 14:04
That repo is the old unsupported one ,but to make sure it isnt a SR bug could you try changing port to 8081 (default) and try out (make sure you are on the new repo)

**Comment by ThePierce** [comment] 2016-01-08 14:22
Tnx for the reply. Maybe a silly question but what is the new repo then? Since when i click on: !!! OFFICIAL SICKRAGE RELEASES DOWNLOAD FROM HERE ONLY !!! at https://sickrage.tv/forums/forum/latest-releases-aa. it gives me the "right" repo

**Comment by duramato** [comment] 2016-01-08 14:23
https://github.com/SickRage/SickRage

**Comment by lokenx** [comment] 2016-01-08 14:25
What he posted, beat me lol

All the devs, besides the original creator (who had been MIA for a number of months) have moved to their own project. Going forward I assume it'll be the defacto, as I don't know what the original creator is doing besides trying to get people to use his repo.

**Comment by ThePierce** [comment] 2016-01-08 15:08
Pfeww done,done and unfortunatly No solution :(

**Comment by ThePierce** [comment] 2016-01-08 15:29
Never mind!! BAM it's working, thanks so much for the quick support guys!

**Comment by duramato** [comment] 2016-01-08 15:29
@ThePierce what worked ? changing repo?

**Comment by ThePierce** [comment] 2016-01-08 15:46
Yes. I changed to the repo you guys advised. After that everything workes as designed.

**Comment by duramato** [comment] 2016-01-08 16:08
@ThePierce Good to hear :)
The new one has received a lot of updates and probably if you had any issues with the old one they are probably now fixed

**Comment by ThePierce** [comment] 2016-01-08 16:12
I sure hope so. The old version was giving me more problems. So thanks again.

**Comment by lokenx** [comment] 2016-01-08 17:53
Not sure why the API would have changed, or maybe it's not the API but something else that is having issues with stuff being added, with the old repo.

Regardless, glad it's working!

**Closed by lokenx** 2016-01-08 17:53 UTC
