### ISSUE TITLE
[Enhancement] Ability to run application from a sub-directory

### ISSUE THREAD

**Issue by pengc99** [lokenx/plexrequests-meteor#88] opened 2015-06-14 09:04 UTC
Running the application with setting the root_url variable set:
`ROOT_URL=http://127.0.0.1:3000/plexrequest/ meteor`

The app starts and lists the new correct root url:
`=> App running at: http://127.0.0.1:3000/plexrequest/ `

However, trying to access the app using the new root-url fails, and displays a 404 error. Admin login doesn't work either, and also displays the same error. 

It looks like in the source, it's still trying to access a few resources without picking up the new root url:
`  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/stylesheets/bootstrap.min.css">
    <link rel="stylesheet" href="/stylesheets/loaders.min.css">
    <link rel="stylesheet" href="/stylesheets/style.css">
    <link rel="icon" href="favicon.ico">`

**Comment by lokenx** [comment] 2015-06-15 14:58
Sorry for late reply, I replied via email but doesn't look like it came through.

>There have been a couple users trying to run from a sub directory but I don't think any have succeeded, if you look at other issues you'll see what they tried.

>Can you not run it from a sub domain instead? From a sub directory is just asking for issues. As well, I honestly don't know how well meteor would handle it.

**Comment by pengc99** [comment] 2015-06-15 18:32
Not a problem. I'm aware that people haven't really had success getting this to work. I'm going to take a hack at it to see if I can get it to work. I have no experience working with Meteor though, so I'll need to take a look at those docs first. If I get it to work I'll submit a pull request with the changes.

**Comment by lokenx** [comment] 2015-06-16 14:51
Just a heads up there are likely many places where there will be issues. I can't remember why, but I removed all instances of using ROOT_URL when creating links and such because they kept causing problems for people and I didn't know any better at time.

But keep me posted and I'll help out as much as I can (although as I'm sure people can tell, updates have slowed a bit as real life gets in the way!).

**Comment by vanstinator** [comment] 2015-06-18 22:37
I'd be interested in this as well. I'm not a JS guy *at all* but I may read up on the docs and take a crack at this. Putting this behind a reverse proxy is currently a PIA, so a root url would make it infinitely easier.

**Comment by mescon** [comment] 2015-08-10 01:14
Has anyone found a way to run this behind a reverse proxy in a subdirectory such as /plexrequest ?

**Comment by pengc99** [comment] 2015-08-24 19:18
I've been working on it in my free time. No success yet, but I will update then when I have progress.

**Comment by lokenx** [comment] 2015-08-24 23:41
Just of note, I'm going through a re-structuring/modularization of the application--not sure how that will impact what you're trying to do. See #101.

**Comment by lokenx** [comment] 2015-10-30 15:17
Can you guys checkout the `sub-directory` branch? I think it works if you pass in ROOT_URL. Not sure how it would work behind a reverse proxy such as nginx but maybe someone can give it a try.

For example, the below makes the application available at `/plex`:

`ROOT_URL=http://localhost:3000/plex meteor`

**Comment by lokenx** [comment] 2015-11-03 01:17
If still a priority let me know, and if my changes didn't work.

**Comment by mescon** [comment] 2015-11-03 15:13
Hey!
How would I go about setting the ROOT_URL in a Windows environment?

**Comment by lokenx** [comment] 2015-11-03 15:15
How are you running it currently? You need to pass `ROOT_URL` on startup or as an environment variable.

`ROOT_URL=http://localhost:3000/plex meteor`

**Comment by mescon** [comment] 2015-11-03 15:21
With a batch-script containing:

   @echo off
   cd \htpc\plexrequests\
   meteor

**Comment by mescon** [comment] 2015-11-03 15:24
Also, I've been on the stable branch the entire time. Can I run the dev branch (I just installed it, I'm just fiddling around), or has the proposed changes not been merged to that branch yet? If so I'll check out the sub-directory branch.

**Comment by lokenx** [comment] 2015-11-03 15:46
The change is current on the sub-directory branch only as I'm not sure if it works as intended yet.

Change your script as below should do the trick

```
@echo off
cd \htpc\plexrequests\
ROOT_URL=http://localhost:3000/plex meteor
```

**Comment by mescon** [comment] 2015-11-03 15:51
Couldn't get the dev nor the sub-directory branch to work. I'm removing everything and starting from scratch instead.
ROOT_URL was not recognized, however this is supposed to work:
```
 set ROOT_URL=http://localhost:3000/plex meteor

**Comment by lokenx** [comment] 2015-11-03 15:52
Ah yeah maybe that's needed for Windows. Let me know

**Comment by mescon** [comment] 2015-11-03 15:55
I moved the installation to my Trisquel (Ubuntu derivative) - currently I've done:

```
git clone https://github.com/lokenx/plexrequests-meteor/ /opt/plexrequests/
cd /opt/plexrequests
git checkout sub-directory
git pull
meteor
```
And then I got this error:

```
[[[[[ /opt/plexrequests ]]]]]

=> Started proxy.
=> Started MongoDB.
Unexpected mongo exit code null. Restarting.

/root/.meteor/packages/meteor-tool/.1.1.10.fhfsom++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at Object.exports.spawn (child_process.js:746:9)
    at spawnMongod (/tools/runners/run-mongo.js:40:24)
    at launchOneMongoAndWaitForReadyForInitiate (/tools/runners/run-mongo.js:454:12)
    at launchMongo (/tools/runners/run-mongo.js:656:7)
    at [object Object]._.extend._startOrRestart (/tools/runners/run-mongo.js:756:19)
    at [object Object].<anonymous> (/tools/runners/run-mongo.js:819:14)
    at runWithEnvironment (/tools/utils/fiber-helpers.js:137:21)
```
Any thoughts?

**Comment by lokenx** [comment] 2015-11-03 15:59
What version of Meteor you got?

`meteor --version`

Can you try the dev?

**Comment by mescon** [comment] 2015-11-03 16:08
I'm currently updating the meteor version - I decided to do that before I saw your message and I didn't check what version I was on already.

I've just updated to 1.2.1 and the app is working now.

However, I set:
```
root@osiris:/opt/plexrequests# ROOT_URL=http://localhost:3000/plexrequests meteor
[[[[[ /opt/plexrequests ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/plexrequests

```
and in my web-frontend (nginx) I set 
```
location /plexrequest {
        proxy_pass      http://localhost:3000/plexrequests;
        include         proxy/proxy-control.conf;

}
```

... the examt same thing I've done with nzbdrone/couchpotato and so on.

Would you prefer we work it out over Skype/TeamViewer/VNC/ssh or are you not in the mood? :-)

**Comment by lokenx** [comment] 2015-11-03 16:11
And that's not working? What you getting when trying to view the page?

I use a sub-directory but let me pull my nginx config up (once I get to a computer). I'm not near a computer! But I think I'm going to see if can setup gitter for this type of troubleshooting.

**Comment by mescon** [comment] 2015-11-03 16:27
The browser only renders "Unknown path".
I also tried to set the base URL to  http://external.name.com/plexrequests/ instead, but then it just rendered an empty page in my browser.

**Comment by lokenx** [comment] 2015-11-03 16:29
Not sure if it helps but my config is below for sub domain.

```
location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # allow websockets
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP
        
        # this setting allows the browser to cache the application in a way compatible with Meteor
        # on every applicaiton update the name of CSS and JS file is different, so they can be cache infinitely (here: 30 days)
        # the root path (/) MUST NOT be cached
        if ($uri != '/') {
            expires 30d;
            }
        }
}
```

**Comment by mescon** [comment] 2015-11-03 16:37
I think it might have to do with a trailing slash.
My start parameters:

```
root@osiris:/opt/plexrequests# ROOT_URL=http://localhost/requests meteor
[[[[[ /opt/plexrequests ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost/requests
```
nginx:
```
location /requests {
        proxy_pass http://localhost:3000/requests;
        include         proxy/proxy-control.conf;
}
```

Before, I might have had ROOT_URL as ROOT_URL=http://localhost/requests/ (note the trailing slash), and also in the nginx conf.

By the way - woah, you updated the design and admin design massively. Awesome job!

**Comment by lokenx** [comment] 2015-11-03 16:39
It's possible, so without the trailing `/` it works with sub-directory?

**Comment by mescon** [comment] 2015-11-03 17:08
Yeah, works beautifully without the trailing slash!

Also - before merging to master, would you mind being more specific about the settings on the admin page?

This is good:
```
Enter the root folder where tv shows are saved. For example C:\Media\TV.
```

This, I have no what to enter in:
```
Enter your sub-directory for Sonarr if used. It should also include the slash (/) at teh start.
```
... do you mean the installation directory? (C:\Program Files\Sonarr\) or do you mean the AppData where settings are stored? (C:\Users\username\AppData\Roaming\Sonarr\) or do you mean something else? What is it used for?
Same thing with CouchPotato.

Otherwise it looks awesome!

**Comment by lokenx** [comment] 2015-11-03 17:11
Great thanks! Ah yes that's an obscure setting if you're running any of those services out of a subdirectory. For example instead of `http://10.0.0.1:5050/` for CP you go to `http://10.0.0.1:5050/couchpotato`.

I'll try and clear those up (and for most people they are to be left blank).

**Comment by mescon** [comment] 2015-11-03 17:12
Ah, thats for people like me then - where my CouchPotato is running behind a reverse proxy :-)
I don't have to use it though, because I can just call on localhost:5050 instead of going via the reverse proxy which is external.name.com/couchpotato.

**Comment by lokenx** [comment] 2015-11-04 15:36
Changes are in `dev` now.

**Closed by lokenx** 2015-11-04 15:36 UTC
Labels: enhancement, help wanted

**Comment by mescon** [comment] 2015-11-04 15:42
Awesome thanks a bunch!

**Comment by rix1337** [comment] 2015-11-06 17:30
How would one go about setting a path prefix. I have set up the latest dev build and can't find an option..

**Comment by lokenx** [comment] 2015-11-06 17:43
You can actually use `master`. Depends how you are running the app. Using just meteor you pass it through using ROOT_URL during startup.

    ROOT_URL=http://localhost/requests meteor

If using nodejs after building the app, you would need to pass it through as an environment variable, which depending how its started determines that.

**Comment by rix1337** [comment] 2015-11-06 17:46
That's fantastic news, thank you for the reply.

I am running the app inside an unRAID docker, which should support setting variables easily

**Comment by lokenx** [comment] 2015-11-06 17:48
Cool, in that case you should pass it through during start-up just like the MongoDB info. I believe you need to omit the trailing slash `/` as well FYI.

**Comment by rix1337** [comment] 2015-11-06 17:50
sounds locial, thanks for the heads up & the cool app!

**Comment by sjfer** [comment] 2015-11-09 17:24
I've noticed that the "Plex Requests" icon in the top left of the page when this is set up takes you to the homepage of the server rather than then what the ROOT_URL is set to. Is there anyway this can be changed?

**Comment by lokenx** [comment] 2015-11-09 17:25
Just fixed it today, give your app an update!

**Comment by sjfer** [comment] 2015-11-09 17:26
Ah thanks! How do I update? Some form of git clone? Or is there another method? I've been struggling to find this out.

**Comment by lokenx** [comment] 2015-11-09 17:28
Depends how you're running it, but yes a `git pull` would work in the directory.

**Comment by sjfer** [comment] 2015-11-09 17:32
Perfect. Thanks for your help! :)
