### ISSUE TITLE
Meteor v1.3 Update Notification / Failed

### ISSUE THREAD

**Issue by jstevenson72** [lokenx/plexrequests-meteor#314] opened 2016-04-03 13:44 UTC
When executing PlexRequests now I get notified of an update to Meteor 1.3.  It says to execute "Meteor Update" within the project directory.  Upon doing so, it throws an exception and stack trace:

```
C:\PlexRequests>meteor update

C:\Users\Plex\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x
86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise
\promise_server.js:116
      throw error;
            ^
Error: Builder can not write without either data or a file path or a symlink pat
h: os/packages/packages.json
    at Builder.write (C:\tools\isobuild\builder.js:251:13)
    at Builder.writeToGeneratedFilename (C:\tools\isobuild\builder.js:382:10)
    at C:\tools\isobuild\isopack.js:1400:27
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Plex\AppData\Local\.meteor\packages\m
eteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\u
nderscore.js:79:11)
    at _.each.builder.copyDirectory.from (C:\tools\isobuild\isopack.js:1372:11)
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Plex\AppData\Local\.meteor\packages\m
eteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\u
nderscore.js:79:11)
    at C:\tools\isobuild\isopack.js:1263:9
    at Isopack._.extend.saveToPath (C:\tools\isobuild\isopack.js:1641:7)
    at C:\tools\isobuild\isopack-cache.js:323:23
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object]._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:260
:18)
    at C:\tools\isobuild\isopack-cache.js:194:16
    at Function.time (C:\tools\tool-env\profile.js:305:10)
    at C:\tools\isobuild\isopack-cache.js:193:17
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object]._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:
184:20)
    at C:\tools\isobuild\isopack-cache.js:75:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\Plex\AppData\Local\.meteor\packages\m
eteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\u
nderscore.js:87:22)
    at [object Object].eachPackage (C:\tools\packaging\package-map.js:49:7)
    at [object Object].buildLocalPackages (C:\tools\isobuild\isopack-cache.js:74
:24)
    at C:\tools\project-context.js:758:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (C:\tools\project-context.js:
757:18)
    at C:\tools\project-context.js:278:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:268:18
)
    at C:\tools\project-context.js:260:12
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:259:13
)
    at C:\tools\cli\commands-packages.js:1523:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:279:29)
    at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1522:8)
    at Command.main.registerCommand.name [as func] (C:\tools\cli\commands-packag
es.js:1594:29)
    at C:\tools\cli\main.js:1408:23

C:\PlexRequests>
```

**Comment by lokenx** [comment] 2016-04-03 13:50
Hmm so far our tests with 1.3 (which changes a lot) seem to have been fine so not sure what happened to yours. Could you maybe delete the packages in the below directory and then when you run `meteor` again it'll download new copies (this can take awhile so be patient).

`C:\Users\USERNAME\AppData\Local.meteor\packages`

Can you also make sure you're up to date with master as well? And post the results of `git status` as well for good measure.

**Comment by jstevenson72** [comment] 2016-04-03 14:16
Looks like after deleting everything in the packages folder, that it destroys the Meteor installation.  I think Meteor itself is in there, and so now I am reinstalling it from their installer.

Here are the results of the git status and update:

```
C:\PlexRequests>git status
On branch master
nothing to commit, working directory clean

C:\PlexRequests>git fetch origin
remote: Counting objects: 52, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 52 (delta 16), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (52/52), done.
From https://github.com/lokenx/plexrequests-meteor
   c215ad5..d32e59b  master     -> origin/master

C:\PlexRequests>git reset --hard origin/master
HEAD is now at d32e59b Poster_Path Fix

C:\PlexRequests>
```

After re-installing it ran fine, but when trying to do the recommended "meteor udpate" it gave the following exception:

```
C:\PlexRequests>meteor
[[[[[ C:\PlexRequests ]]]]]

=> Started proxy.
=> Meteor 1.3 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

I20160403-09:14:08.114(-5)? No change detected for the collection tv
I20160403-09:14:08.114(-5)? No change detected for the collection movies
I20160403-09:14:08.114(-5)? No change detected for the collection settings
Terminate batch job (Y/N)? y

C:\PlexRequests>meteor update

C:\Users\Plex\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x
86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise
\promise_server.js:116
      throw error;
            ^
Error: Builder can not write without either data or a file path or a symlink pat
h: os/packages/packages.json
    at Builder.write (C:\tools\isobuild\builder.js:251:13)
    at Builder.writeToGeneratedFilename (C:\tools\isobuild\builder.js:382:10)
    at C:\tools\isobuild\isopack.js:1400:27
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Plex\AppData\Local\.meteor\packages\m
eteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\u
nderscore.js:79:11)
    at _.each.builder.copyDirectory.from (C:\tools\isobuild\isopack.js:1372:11)
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Plex\AppData\Local\.meteor\packages\m
eteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\u
nderscore.js:79:11)
    at C:\tools\isobuild\isopack.js:1263:9
    at Isopack._.extend.saveToPath (C:\tools\isobuild\isopack.js:1641:7)
    at C:\tools\isobuild\isopack-cache.js:323:23
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object]._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:260
:18)
    at C:\tools\isobuild\isopack-cache.js:194:16
    at Function.time (C:\tools\tool-env\profile.js:305:10)
    at C:\tools\isobuild\isopack-cache.js:193:17
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object]._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:
184:20)
    at C:\tools\isobuild\isopack-cache.js:75:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\Plex\AppData\Local\.meteor\packages\m
eteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\u
nderscore.js:87:22)
    at [object Object].eachPackage (C:\tools\packaging\package-map.js:49:7)
    at [object Object].buildLocalPackages (C:\tools\isobuild\isopack-cache.js:74
:24)
    at C:\tools\project-context.js:758:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (C:\tools\project-context.js:
757:18)
    at C:\tools\project-context.js:278:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:268:18
)
    at C:\tools\project-context.js:260:12
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:259:13
)
    at C:\tools\cli\commands-packages.js:1523:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:279:29)
    at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1522:8)
    at Command.main.registerCommand.name [as func] (C:\tools\cli\commands-packag
es.js:1594:29)
    at C:\tools\cli\main.js:1408:23

C:\PlexRequests>
```

**Comment by lokenx** [comment] 2016-04-03 14:19
Hmm OK. I don't know if @rigrassm was running his 1.3 branch on Windows or what but let me try a few things.

I've seen a few issues with 1.3 and Windows but this doesn't seem related to any of those. For the moment, don't do the `meteor update`, things will work fine without doing the update.

**Comment by jstevenson72** [comment] 2016-04-19 14:45
OK.  Thanks for the advice.  Keep up the good work!

**Comment by rsissons** [comment] 2016-04-26 02:36
I have the same exact message as jstevenson. 

C:\Users\Plex\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x
86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise
\promise_server.js:116
      throw error;
            ^
Error: Builder can not write without either data or a file path or a symlink pat
h: os/packages/packages.json


I don't want to wipe out the installation like he did.

Windows 7 OS.

**Comment by lokenx** [comment] 2016-04-27 00:49
Hmm that's for letting me know @rsissons , I can't seem to get mine to break. But I'm going to spin up some VM's tomorrow and try and let you know!

**Comment by overdox** [comment] 2016-04-27 17:26
I don't about windows, but upgrading meteor to version 1.3.2-rc5 seemed to work for me on linux.

**Comment by rsissons** [comment] 2016-04-27 18:22
Hi, I am glad the upgrade went well for you on linux, but there is
obviously something up with the upgrade on Windows with the

C:\Users\Plex\AppData\Local.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x
86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise
\promise_server.js:116
throw error;
^
Error: Builder can not write without either data or a file path or a
symlink pat
h: os/packages/packages.json

Ron Sissons
rgs@thesissons.com

**Comment by lokenx** [comment] 2016-04-27 18:27
I'm thinking we may have to update how we do the npm package(s) we use to the new 1.3 meteor way. Going to make a branch tonight and see how it goes and if an in-place upgrade will fix it.

**Comment by rigrassm** [comment] 2016-04-27 19:05
Check out the [issue](https://github.com/meteor/meteor/issues/6609) on meteors gituhub. Seems that some filepaths get too long (NTFS has a character limit for filepaths) causing Meteor to fail to load files. Try deleting the %appdata%\local\.Meteor\Packages folder and then running Meteor 1.3.

**Comment by overdox** [comment] 2016-04-27 19:32
I had similar issue on linux with meteor version 1.3.0. But after I cleaned the installation and upgraded to 1.3.2 rc5 from the beta branch, it ran fine. Could be worth a shot to try out the latest beta.

**Comment by lokenx** [comment] 2016-04-27 22:34
Meteor 1.3 has had some growing pains with Windows especially so I wouldn't be surprised an update could tentatively fix this issue.

**Comment by rigrassm** [comment] 2016-04-27 23:52
I finally broke down and installed Meteor on a Windows machine so I'll be able to test some of this now. Updating may fix the issue but you still may need to delete that packages path from the prior install so it can be rebuild.

**Comment by rigrassm** [comment] 2016-04-28 02:43
I just ran the following test.

1. installed meteor on windows
2. clone master repo and run meteor - Successfully running with 1.2.1
3. run meteor update - updates to 1.3.x.x and successfully runs
4. pulled my existing app running on my linux server to the windows machine - Successfully ran with 1.2.1
5. ran meteor update on that one and again it updates, builds and runs 1.3.x.x successfully

It seems that the issue is resolved with the latest meteor update as I couldn't get the app to fail whether running from a fresh clone or one that has been in use(on a linux machine at that).

**Comment by rsissons** [comment] 2016-04-28 14:55
OK Thanks.

So what is the process I should take to uninstall\reinstall?

Ron Sissons
rgs@thesissons.com

**Comment by rigrassm** [comment] 2016-04-28 16:02
I personally would just backup your existing db folder, do a git pull of the plexrequests-meteor, run `Meteor update`, then run `meteor`.

Once you have it to send running, just copy your backed up db folder into the new app and restart.

**Comment by rigrassm** [comment] 2016-04-30 19:52
@rsissons any luck?

**Comment by rsissons** [comment] 2016-05-01 15:14
I haven't got to it just yet. I will post once I do. Thanks

**Comment by didyouexpectthat** [comment] 2016-05-10 04:35
I ran fine on 1.3 until I pulled new files down. Then it was throwing errors. I just hard reset plexrequests and everything was back to normal.

**Comment by rigrassm** [comment] 2016-05-10 04:49
I haven't run into any issues either from a clean install. In fact, things seem to be running better as far as build times go. I can't speak for Windows but at least on Linux it seems safe to update. Just backup and pull down a clean install to be safe.

**Comment by rigrassm** [comment] 2017-02-19 20:04
Closing since the application has been running on updated meteor versions successfully for quite a while now.

**Closed by rigrassm** 2017-02-19 20:04 UTC
Labels: active, bug, help wanted, research
