### ISSUE TITLE
Some Cover Art Not Loading

### ISSUE THREAD

**Issue by david-zaletanski** [lokenx/plexrequests-meteor#522] opened 2018-01-30 19:49 UTC
A number of movies have broken image icons. Searched for similar Issues but the closest one didn't seem to fit.

![image](https://user-images.githubusercontent.com/5800264/35587501-a1e1d56c-05c3-11e8-8bfa-d80cb01fe74f.png)

Sample of image link, which opening in browser gives an error page saying "Image size not supported".
https://image.tmdb.org/t/p/w184/kBf3g9crrADGMc2AMAMlLBgSm2h.jpg

It's a fresh install as if today, and users connect to it through a reverse proxy, if that makes any difference?
First time trying plexrequests, please forgive if I've missed something! Looks awesome otherwise just wanted to let you know.

**Comment by hossdawg** [comment] 2018-02-08 21:27
The issue is with themoviedb.org. They changed the size of the poster so some are not showing up. I was having the same issue. Edited the "client/templates/search/item.html" and changed the line  

<img src="https://image.tmdb.org/t/p/w184{{poster_path}}" class="img-responsive" alt="Poster">

to...

<img src="https://image.tmdb.org/t/p/w154{{poster_path}}" class="img-responsive" alt="Poster">

And the issue was fixed. The posters are a tad smaller but every poster shows.

**Comment by rigrassm** [comment] 2018-02-11 08:17
I just pushed a commit that will remedy this issue as well as make some of the poster displaying functionalities consistent across both the search and requests page.

Release v1.21.1 was just published so if you are pulling straight from the repo it's there, if you are using the Linuxserver.io docker container it will probably be Friday when the container is rebuilt against this release.

**Comment by rigrassm** [comment] 2018-02-21 01:45
Issue resolved with release v1.21.1

**Closed by rigrassm** 2018-02-21 01:45 UTC

**Comment by david-zaletanski** [comment] 2018-02-21 05:27
Thank you @hossdawg @rigrassm for investigating and resolving!
