### ISSUE TITLE
Request: Add option to download first *n* episodes of season *n*

### ISSUE THREAD

**Issue by philipsd6** [lokenx/plexrequests-meteor#389] opened 2016-07-27 14:43 UTC
Right now, when requesting a new TV show, the only options are **All Episodes** or **New Episodes**. But I have limited space on my Plex box, so it's better if I can just get the first _n_ episodes of whatever season is desired &mdash; maybe the latest season or the first season. Otherwise, my users will either use up all my disk space or be disappointed when they can't start watching from the beginning.

Perhaps in addition to the existing options, a **Custom...** option can be added, where the specific seasons and episodes can be requested?

Or alternatively, as admin I could limit the **All Episodes** option to retrieving the first _n_ results...

**Comment by rigrassm** [comment] 2017-02-19 20:53
Related to and close enough to be considered a duplicate of of #345. More granular TV series control is on the radar and I'm trying to keep the discussion about it in one feature request for easier tracking.

Going to close this issue out but I'd love to see your input over in the other feature request!

**Closed by rigrassm** 2017-02-19 20:53 UTC
Labels: duplicate, enhancement
