### ISSUE TITLE
Sonarr Series Get -> ETIMEDOUT

### ISSUE THREAD

**Issue by loeschj** [lokenx/plexrequests-meteor#244] opened 2016-01-22 04:15 UTC
I have everything setup in the Sonarr Tab, getting successful tests, when i approve it is adding the show, but everytime i request or approve i see "Sonarr Series Get -> ETIMEDOUT" in the log and i'm not sure what the problem is.

Sonarr 2.0.0.3766

PlexRequests 
Branch: master
Version: 1.5.0

**Comment by lokenx** [comment] 2016-01-22 13:45
What's your `lokenx:sonarrwrapper` version in `.meteor/versions`?

**Comment by m1e1w1** [comment] 2016-01-22 16:02
![sonarrcap2](https://cloud.githubusercontent.com/assets/6841054/12515696/646bd4fc-c0de-11e5-9628-1cff4860ceab.PNG)
similar issue? my version of sonarrwrapper is 0.0.8.

**Comment by loeschj** [comment] 2016-01-23 00:46
lokenx:sonarrwrapper@0.0.8

**Comment by jjbrunton** [comment] 2016-01-25 19:07
Same issue

**Comment by lokenx** [comment] 2016-01-26 20:28
The error with the posts is a missing tvdb for the show. The constant get errors I'm looking into, but my test install of Sonarr does't seem to have them. Do you have a large library? Can you ping the sonarr machine if it's different from the plex requests machine and let me know how long it takes. It could be the request is taking to long and PR gives up.

**Comment by m1e1w1** [comment] 2016-01-26 23:32
For my install, the sonarr install is a different machine. i can ping the ip address of the machine from the machine where plex requests is installed through CMD prompt with no loss.
my tv shows library is about 230 series within sonarr (active). my plex library has over 460+ series and most not tracked through sonarr (off air).

so, not very sure on exactly what i should be calling with requests, but i did try http://myip:8989/myapikey/calendar and i get sonarr to load, but the calendar itself never loads.
http://myip:8989/calendar loads fine.
i was also asked to enter my authentication credentials. 
i tried http://myip:8989/api and i get unauthorized and with http://myip:8989/myrealapikey
i get sonarr page to load. but nothing happens when i try to use the commands such as series/ calendar/ as sonarr loads, but what ever page it wants to pull up never loads in, so i get menus and background only.

**Comment by lokenx** [comment] 2016-01-27 00:44
The end point that seems to be timing out is the `Series` one. You need to authenticate with a header attribute which you can't do in a browser window so you'll need Postman or something like curl installed, or using a query parameter. The below call for my test install takes 60ms but it only has 4 series in it.

```
Update with your appropriate details

http://localhost:8989/api/series?apikey=abcd1234

Returns an array containing all series in Sonarr, it's needed to get the Sonarr ID number.
```

If it is a timeout issue due to this call taking to call, the good news is it wont exist in the next version as I'll be asking Plex for the show stats.

**Comment by m1e1w1** [comment] 2016-01-27 02:26
That URL worked, i had been putting the wrong format for the url.

I tested your's and put in my api key and ip of sonarr, the list loaded in about 6 seconds id say. It looks exactly like the type of data suggested from the API documentation for sonarr, so successful id say.

what do you think?

**Comment by lokenx** [comment] 2016-01-27 02:44
Yep, but the issue is the 6 seconds part. The original timeout was 2 for the request! I bumped it up to 5 seconds earlier this evening, but I'll bump it up to 15 seconds just to be safe. Hopefully that fixes some issues.

**Comment by loeschj** [comment] 2016-01-27 05:27
i did the above as well and it took 8 seconds for the page to load.

**Comment by m1e1w1** [comment] 2016-01-27 05:49
cool, seems like a good thing to set at 15 seconds. what version are we looking at for an update? sonarr wrapper 0.0.10, plex requests 1.5.2? 
versions 0.0.9, 1.5.1 still produce the error.

**Comment by lokenx** [comment] 2016-01-27 18:14
It'll be `0.0.10` and `1.5.2` yeah. The version I just did was only up to 5 seconds. I'll change it later today.

**Comment by lokenx** [comment] 2016-01-27 22:04
Update was pushed as seen above, let me know how things are working for you guys now!

**Comment by m1e1w1** [comment] 2016-01-28 08:48
for me, the update to version 0.0.10, 1.5.2 did not solve the ETIMEDOUT error. Sonarr Series State -ETIMEDOUT, as well as Get - ETIMEDOUT and Post - expected string, got undefined; errors.

i attempted to add a known show, which has a TVDB id, and approve it. wont approve. may be additional underlining problem? 

should i try a local install of sonarr to test? my sonarr install is on a different machine, on the same network though.

**Comment by lokenx** [comment] 2016-01-28 15:30
@m1e1w1 can you try this from the machine that is running Plex Requests?

```
Update with your appropriate details

http://localhost:8989/api/series?apikey=abcd1234

Returns an array containing all series in Sonarr, it's needed to get the Sonarr ID number.
```

**Comment by loeschj** [comment] 2016-01-28 23:19
@lokenx I just updated and it's working just fine! The only thing i would suggest is if you can make the request button animate or something happen on the page to let me know that it's "thinking". I wasn't entirely sure if it went through until the button changed to "downloaded".

**Comment by lokenx** [comment] 2016-01-28 23:20
I thought it did...but I could be confusing buttons!

**Comment by m1e1w1** [comment] 2016-01-29 00:09
@loeschj 
I tested the URL again, with my info and the page loads in about 8 seconds each time.

**Comment by lokenx** [comment] 2016-01-29 00:12
But you can't approve requests? Weird I've given it 15 seconds to work...

**Comment by m1e1w1** [comment] 2016-01-29 13:44
Yeah, still cant add a series from Plex Requests. I tried a fresh plex requests install, followed by installing a fresh copy of sonarr for windows, for localhost so its the same machine as my plex requests. updated sonarr and fully setup with no series at all. blank slate.
rebooted plex requests: i get this;

![sonarr3](https://cloud.githubusercontent.com/assets/6841054/12677065/4a4f1e5e-c64b-11e5-85b8-7a7ca4063f5e.PNG)

errors above the reboot where the remote sonarr client i normally use.

**Comment by lokenx** [comment] 2016-01-29 13:50
The post errors are because it didn't get a TVDB ID number. I'll investigate today why that isn't getting caught and stopped from posting.

Is your API key correct, the unauthorized errors seem to be Sonarr kicking you back.

**Comment by m1e1w1** [comment] 2016-01-29 14:51
Yeah, I did have 2 extra spaces in the api key when I copied it to plex requests, I had fixed that, then rebooted plex requests. After the reboot, I just got the post no ID error, no get ETIMEDOUT error. 
Plex requests let me search and add the request, just can't approve.
In sonarr, I can add and download episodes for the same show.

**Comment by lokenx** [comment] 2016-01-29 14:55
Yeah the post is because the TMDB doesn't have an TVDB ID for the show which is required by Sonarr to add a new show. I can't fix that unfortunately, you'd have to go on TMDB and contribute the TVDB to the show in their db.

The next version will use the TVDB directly with their new API. Can you try another show to make sure it's working fine for those that do have TVDB ID's?

**Comment by m1e1w1** [comment] 2016-01-29 22:29
That i did, i went to TheTVDB.com, and looked up Over the Garden Wall, ID 281643. when adding it to plex requests, approve fails. when adding it directly to sonarr, no problems.

**Comment by lokenx** [comment] 2016-01-29 22:33
No I think you're mixing the two up. We use TMDB for searches, but TV shows require a TVDB ID to be added to Sonarr. Sometimes TMDB doesn't have a TVDB because no one has added it yet.

It would work fine through Sonarr because they use the TVDB API, I don't because the search results were poor. We will be using the new TVDB API going forward.

Please try a different show to confirm it's working. Some shows will never work because of the above.

**Comment by m1e1w1** [comment] 2016-01-29 22:55
The movie database website dose list Over the Garden Wall. @ https://www.themoviedb.org/tv/61617-over-the-garden-wall?language=en 
its id i assume is 61617. so i believe it should work but is failing.

**Comment by lokenx** [comment] 2016-01-29 23:07
TheMovieDB ID number is different than the TVDB ID number. Can you try something else like a CSI or Big Bang or something and see what happens?

**Comment by m1e1w1** [comment] 2016-01-29 23:09
sure. - ill update this post with the results of that.

**Comment by lokenx** [comment] 2016-01-30 00:53
Hmm, interesting. Can you let me know your versions?

**Comment by m1e1w1** [comment] 2016-01-30 02:45
Sonarr remote and local versions are the same. @ 2.0.0.3778 Developer branch

Plex Requests version @ 1.5.2

anything else more specific?

**Comment by mescon** [comment] 2016-02-19 15:05
I'm still having this issue on PlexRequests 1.6.0 and Sonarr 2.0.0.3732 (latest).
In fact, if I start PlexRequests, Sonarr crashes for some reason. May be a Sonarr issue, I don't know.

**Comment by lokenx** [comment] 2016-02-19 15:18
@mescon haha what, that sounds weird!

The `Sonarr Series Post` errors from above are because it's not being parse a TVDB ID number from TheMovieDB to add to Sonarr. I'm not sure if it's the API not responding, hitting an API limit, or what exactly. @mescon is that the error you get, or is it something different? Are you Sonarr quality profiles populating correctly?

**Comment by mescon** [comment] 2016-02-19 15:28
@lokenx It seems to have been a RAM memory issue - when I installed swapspace (``apt-get install swapspace``), the problem went away.I'll write here again if the problem persists.

**Comment by lokenx** [comment] 2016-02-20 21:25
@loeschj hasn't posted in awhile, so I'm closing this. If you've a similar issue please open another ticket, this one's gotten long and wayward!

**Closed by lokenx** 2016-02-20 21:25 UTC
