### ISSUE TITLE
[Bug] Windows Dropdown Issue

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#138] opened 2015-10-30 01:29 UTC
When i Click the report issue the button lights up but i'm not provided with any options.

-Steps
Click Requests 
then Click "Report Issue"
no options display

**Comment by lokenx** [comment] 2015-10-30 01:37
Any console error messages? What version? What platform is it running on? What platform are you trying to do the above on?

**Comment by unixjeff** [comment] 2015-10-30 01:48
Version: v0.6.15

Terminal

=> App running at: http://localhost:3000/
I20151029-21:14:45.164(-4)? Adding default settings
I20151029-21:16:34.675(-4)? Exception while invoking method 'getBranch' undefined
I20151029-21:16:34.935(-4)? Exception while invoking method 'checkForUpdate' undefined
I20151029-21:16:52.690(-4)? Exception while invoking method 'getBranch' undefined
I20151029-21:16:52.949(-4)? Exception while invoking method 'checkForUpdate' undefined

**Comment by lokenx** [comment] 2015-10-30 01:52
Hmm those aren't anything interesting (they're being removed in next push).

Can you use Chrome and check the [developer console](https://developer.chrome.com/devtools).

Also what OS is the server on and what are you on?

**Comment by unixjeff** [comment] 2015-10-30 01:58
Ubuntu Linux 14.04.2

-Console
Uncaught TypeError: Cannot read property 'appendChild' of null(anonymous function) @ main.js:193(anonymous function) @ main.js:198

**Comment by lokenx** [comment] 2015-10-30 01:59
What Chrome version, and what you running Chrome on?

**Comment by unixjeff** [comment] 2015-10-30 02:00
Chome Version 46.0.2490.80 m (64-bit)
WIndows 10 PRO

I also tried Edge and same results

**Comment by RandomNinjaAtk** [comment] 2015-10-30 03:02
Reporting feature doesn't work on the Dev after the update for me also on both Chrome and Edge

**Comment by lokenx** [comment] 2015-10-30 03:06
But it did in v0.6 branch? I didn't touch anything there for awhile!

It's working for me in Server 2012 and IE 10.

What OS version?

**Comment by RandomNinjaAtk** [comment] 2015-10-30 03:12
Windows 10 Pro Insider build 10565

It did work previously in the v0.6 branch, but I had moved my main back to the dev. So the latest updates over the past few days to the V0.6, I had not tested.

**Comment by lokenx** [comment] 2015-10-30 03:13
Can you test the requesting of a TV show @RandomNinjaAtk? Does that dropdown work?

I'm going over commits to see what's changed of note regarding those areas.

**Comment by RandomNinjaAtk** [comment] 2015-10-30 03:16
Nope doesn't work. Tested in Chrome and MS Edge

**Comment by ashleytayles** [comment] 2015-10-30 03:16
Doesn't work for me.
Browser: IE11 / Chrome Stable
OS: Windows Server 2012R2
Branch: v0.6

New install as of about 30 mins ago.

If needed I can set up remote access to the server I have this installed on. I can also set up a quicky Win10 VM if needed.

**Comment by ashleytayles** [comment] 2015-10-30 03:19
In regards to my above comment > Movies work fine, TV shows do not.

**Comment by lokenx** [comment] 2015-10-30 03:24
Yeah Movie requests don't have a dropdown. TV requests and all issue reporting have drop downs.

It's late here but I'll have a look first thing tomorrow morning Should have some Windows 10 VM's on old ESXi host.

Sorry guys, hope to get fixed ASAP!

**Comment by ashleytayles** [comment] 2015-10-30 03:27
@lokenx 

I'm on v0.6 and this is happening to me :)

**Comment by lokenx** [comment] 2015-10-30 03:30
@ashleytayles thanks! Will have more info tomorrow hopefully...

**Comment by lokenx** [comment] 2015-10-30 03:43
@unixjeff or anyone else whose familiar with Chrome Dev tools, determine what `.js` file that's causing the issue? `main.js` doesn't help as I don't have any files named like that.

Can't check myself as still waiting on Win10 to get up and running.

**Comment by JibbsIsMe** [comment] 2015-10-30 04:03
My friend and I both tested this in Chrome, and neither of us could find any errors at all. It seems like it's not even trying to do anything.

**Comment by JibbsIsMe** [comment] 2015-10-30 04:08
Try this. I changed the port and removed my API keys for security reasons, but you should still be able to see the dropdown issue. 

http://my.jeremyk.net:26898/

**Comment by ashleytayles** [comment] 2015-10-30 04:25
Also just tested on my phone.
Nexus 5
Android 6.0.0
Chrome 46.0.2490.76

I still get the Dropdown issue on branch v0.6.

Tested on my desktop here at work,
Windows 7
Chrome
IE 11

The issue is also present.

**Comment by lokenx** [comment] 2015-10-30 11:30
Huh, confirmed @JibbsIsMe installation is having same issue on my machines, seems only my installation is working!

I've created a new branch for testing, `dropdown-issue`, switch to it to test out fix. I'll merge back once it's working.

**Comment by pickthenimp** [comment] 2015-10-30 13:54
Confirmed fixed on my end using the dropdown-issue branch!

**Comment by SupFrost** [comment] 2015-10-30 14:25
The issue is fixed for me as well :)
Thanks a lot!

**Comment by lokenx** [comment] 2015-10-30 14:49
Update to `0.6.16`.

**Closed by lokenx** 2015-10-30 14:49 UTC
Labels: bug
